---
title: "06_LCP_conductance"
author: "Matt DeSaix"
date: "2025-03-27"
output: html_document
---

```{r}
library(terra)
library(tidyverse)
library(leastcostpath)
library(tidyterra)
library(geosphere)
library(viridis)
```


```{r}
fitted_conductance_4agg <- rast("./out/radish/30m_4agg/hpc_summaries/elev_slope_roads_canopy/64PCs_4agg.elev_slope_roads_canopy.conductance_raster.tif")

meta <- read_csv("./data/genotypes/buffer-10k/grsm-10k-meta.csv",
                 show_col_types = FALSE) %>%
  mutate(CollectionDate = as.Date(CollectionDate, format = "%m/%d/%Y"),
         Month_day = as.numeric(paste0(month(CollectionDate), ".", sprintf("%02d", day(CollectionDate)))),
         Season = ifelse(Month_day >= 4.01 & Month_day <= 8.14, "Summer", 
                         ifelse(Month_day >= 8.15 & Month_day <= 10.31, "Fall",
                                ifelse(Month_day >= 11.01 | Month_day <= 3.31, "Winter",
                                       "Unknown"))))

meta.lat.long <- meta %>%
  select(SubjectID, Lat, Long, CollectionDate)

full.kinship <- read_csv("./out/pcair-relate/buffer-10k/GSMNP-PCRelate-Kinship-3PCs.csv",
                         show_col_types = FALSE) %>%
  left_join(meta.lat.long, by = c("ID1" = "SubjectID")) %>%
  left_join(meta.lat.long, by = c("ID2" = "SubjectID")) %>%
  mutate(Relationship = ifelse(kin < 0.125, "Distant",
                               ifelse(kin >= 0.125 & kin < 0.25, "2nd",
                                      ifelse(kin >= 0.25 & k0 < 0.1, "Parent-offspring", "Siblings"))),
         Days = abs(as.numeric(difftime(CollectionDate.x, CollectionDate.y, units = "days")))) %>%
  rowwise() %>%
  mutate(Distance = distGeo(p1 = c(Lat.x, Long.x), p2 = c(Lat.y, Long.y))/1000)

kins.coords <- full.kinship %>%
  # filter(Relationship %in% c("Siblings", "Parent-offspring"),
  #        Distance > 0.5) %>%
    # filter(Relationship %in% c("Siblings", "Parent-offspring"),
    #      Distance > 0.2) %>%
  filter(Relationship %in% c("Siblings", "Parent-offspring"),
         Distance >= 0.1) %>%
  select(ID1, ID2, Lat.x, Long.x, Lat.y, Long.y, Relationship, Distance)
kins.coords
```


```{r}
plot(log(fitted_conductance_4agg))
```


```{r}
origin.pts <- kins.coords[,c("Long.x", "Lat.x", "Relationship", "ID1", "ID2")] %>%
  vect(geom = c("Long.x", "Lat.x"))
dest.pts <- kins.coords[,c("Long.y", "Lat.y", "Relationship", "ID1", "ID2")] %>%
  vect(geom = c("Long.y", "Lat.y"))
conductanceMatrix <- create_cs(x = fitted_conductance_4agg)
  
  
lcps1 <- create_lcp(x = conductanceMatrix,
                    origin = origin.pts[1,],
                    destination = dest.pts[1,])
plot(lcps1)
```

```{r}
lcp.list <- list()
for(i in 1:nrow(kins.coords)){
  lcp.list[[i]] <- create_lcp(x = conductanceMatrix,
                              origin = origin.pts[i,],
                              destination = dest.pts[i,])
}

lcp.vect <- vect(lcp.list)
lcp.vect$Relationship <- origin.pts$Relationship
lcp.vect$Distance <- kins.coords$Distance
plot(lcp.vect)
```

```{r}

p.lcps <- kins.coords %>%
  mutate(Relationship = factor(Relationship, levels = c("Siblings", "Parent-offspring"))) %>%
  ggplot() +
  geom_spatraster(data = log(fitted_conductance_4agg)) +
  scale_fill_viridis(name = "Conductance") +
  geom_spatvector(data = lcp.vect %>% mutate(Relationship = factor(Relationship, levels = c("Siblings", "Parent-offspring"))), linewidth = 1, aes(color = Relationship)) +
  geom_point(aes(x = Long.x, y = Lat.x)) +
  geom_point(aes(x = Long.y, y = Lat.y)) +
  scale_color_manual(values = c("purple", "darkgreen")) +
  theme_bw() +
  xlab("Longitude") +
  ylab("Latitude") +
  scale_y_continuous(breaks = seq(35.4, 35.8, by = 0.1)) +
  facet_wrap(~Relationship,
             ncol = 1) +
  theme(panel.grid = element_blank(),
        axis.text.x = element_text(angle = 45, vjust = 1, hjust=1))

ggsave(plot = p.lcps,
       filename = "./plots/LCP/p.lcps_kin_minDist0.1km.conductance_rast.agg4_full_model.png",
       width = 10, height = 8)

p.lcps
```



```{r}
lcp.length <- perim(lcp.vect)/1000
kins.coords$lcp_length <- lcp.length
kins.lcp.sum <- kins.coords %>%
  mutate(Relationship = factor(Relationship, levels = c("Siblings", "Parent-offspring"))) %>%
  group_by(Relationship) %>%
  summarize(N = n(),
            Lin_dist_mean = mean(Distance),
            Lin_dist_median = median(Distance),
            LCP_dist_mean = mean(lcp_length),
            LCP_dist_median = median(lcp_length))
write_csv(kins.lcp.sum, "./plots/LCP/p.lcps_kin_minDist0.1km.summary.csv")
kins.lcp.sum
```

```{r}
kins.coords %>%
  rename("Linear_distance" = "Distance",
         "LCP_distance" = "lcp_length") %>%
  pivot_longer(cols = c(Linear_distance, LCP_distance), 
               names_to = "Measurement", values_to = "Distance(km)") %>%
  ggplot() +
  geom_boxplot(aes(x = Relationship, y = `Distance(km)`, color = Measurement)) +
  theme_bw()
```

