---
title: "PCA and more with Smokies pigs"
author: "Matt DeSaix"
date: "2025-03-2025"
output: html_document
---

```{r, message = FALSE, warning = FALSE}
library(tidyverse)
library(adegenet)
library(geosphere)
library(spdep)
library(RColorBrewer)
```

```{r, warning = FALSE, message = FALSE}
meta <- read_csv("./data/genotypes/buffer-10k/grsm-10k-meta.csv",
                 show_col_types = FALSE) %>%
  mutate(CollectionDate = as.Date(CollectionDate, format = "%m/%d/%Y"),
         Month_day = as.numeric(paste0(month(CollectionDate), ".", sprintf("%02d", day(CollectionDate)))),
         Season = ifelse(Month_day >= 4.01 & Month_day <= 8.14, "Summer", 
                         ifelse(Month_day >= 8.15 & Month_day <= 10.31, "Fall",
                                ifelse(Month_day >= 11.01 | Month_day <= 3.31, "Winter",
                                       "Unknown"))))
geno <- read.PLINK("./data/genotypes/buffer-10k/grsm-10k-final-571_10508.raw")
geno.genind <- dartR::gl2gi(x = geno)
geno.xy <- tibble("SubjectID" = geno$ind.names) %>%
  left_join(meta %>% dplyr::select(SubjectID, Long, Lat), by = "SubjectID") %>%
  dplyr::select(-c(SubjectID)) %>%
  as.matrix()
geno$other$xy <- geno.xy
obj <- tab(geno, freq = TRUE, NA.method = "mean")

# pca distance
pca.geno <- dudi.pca(obj, center = TRUE, scale = FALSE, nf=100, scannf = FALSE)
pca.dist.mat <- as.matrix(dist(pca.geno$li[,1:64]))

# # proportion of alleles shared
# geno.genind <- dartR::gl2gi(geno)
# prop.dist <- propShared(geno.genind)
# 
# # euclidean distance
# # genetic.dist.mat <- as.matrix(dist(obj, method = "euclidean"))
# # genetic.dist <- genetic.dist.mat[lower.tri(genetic.dist.mat)]
# 
# saveRDS(pca.dist.mat, "./data/radish/genetics/pca.dist.mat.64PCs.Rds")
# saveRDS(prop.dist, "./data/radish/genetics/prop.dist.Rds")

geno
```



```{r}
screeplot(pca.geno)
```

```{r}
round(pca.geno$eig / sum(pca.geno$eig), 3)[1:10]
```


```{r}
pca.df <- pca.geno$li %>%
  dplyr::select(Axis1:Axis5) %>%
  rownames_to_column("SubjectID") %>%
  pivot_longer(cols = Axis1:Axis5, names_to = "PC_x", values_to = "val_x" ) %>%
  left_join(pca.geno$li %>% dplyr::select(Axis1:Axis5) %>% rownames_to_column("SubjectID"),
            by = "SubjectID") %>%
  pivot_longer(cols = Axis1:Axis5, names_to = "PC_y", values_to = "val_y") %>%
  mutate(PC_x = gsub(pattern = "Axis", replacement = "PC", PC_x),
         PC_y = gsub(pattern = "Axis", replacement = "PC", PC_y)) %>%
  left_join(meta, by = "SubjectID")

# write_csv(pca.df, "./out/population-structure/grsm-10k-571_10508.pca.df.csv")
pca.df
```


```{r}
pca.df <- read_csv("./out/population-structure/grsm-10k-571_10508.pca.df.csv",
                   show_col_types = FALSE)
p.pca.full <- pca.df %>%
  mutate(val_x = -1 * val_x) %>%
  ggplot() +
  geom_point(aes(x = val_x, y = val_y, color = Long)) +
  scale_color_continuous(name = "Longitude",
                         type = "viridis", option = "A") +
    xlab("PC value (x)") +
  ylab("PC value (y)") +
  facet_grid(PC_y~PC_x) +
  theme_bw()

# ggsave(plot = p.pca.full,
#        filename = "./plots/population_structure/p.pca.full.png")

p.pca.full
```


```{r}
p.pca.1_2 <- pca.df %>%
  filter(PC_x == "PC1",
         PC_y == "PC2") %>%
  mutate(val_x = -1 * val_x) %>%
  ggplot() +
  geom_point(aes(x = val_x, y = val_y, color = Long),
             size = 2) +
  scale_color_continuous(name = "Longitude",
                         type = "viridis", option = "A") +
  xlab("PC1 (5.0% variation)") +
  ylab("PC2 (2.7% variation)") +
  # facet_grid(Sex~County) +
  theme_bw()

# ggsave(plot = p.pca.1_2,
#        filename = "./plots/population_structure/p.pca.1_2.png",
#        width = 10, height = 4)
p.pca.1_2
```

```{r}
cluster_cols <- brewer.pal(n = 5, name = "Dark2")
q_df_arrange_k2 <- read_csv("./out/snmf/q_df_arrange_k2.csv",
                            show_col_types = FALSE)
k2_pop_meta <- q_df_arrange_k2 %>%
  rowwise() %>%
  mutate(Pop_K2 = which.max(c(K1, K2))) %>%
  select(SubjectID, K1, K2, Pop_K2)

p.pca.1_2.k2 <- pca.df %>%
  filter(PC_x == "PC1",
         PC_y == "PC2") %>%
  left_join(k2_pop_meta, by = "SubjectID") %>%
    mutate(Pop_K2 = ifelse(K1 < 0.6 & K2 < 0.6, NA, Pop_K2)) %>%
  mutate(Pop_K2 = factor(Pop_K2)) %>%
  ggplot() +
  geom_point(aes(x = val_x, y = val_y, color = Pop_K2),
             size = 2) +
    scale_color_manual(name = "Genetic cluster",
                    values = c("grey80", cluster_cols[c(2,1)]),
                    breaks = c(NA, 2, 1),
                    labels = c("NA", "K1", "K2")) +
  xlab("PC1 (4.9% variation)") +
  ylab("PC2 (2.7% variation)") +
  theme_bw()

# ggsave(plot = p.pca.1_2.k2,
#        filename = "./plots/population_structure/p.pca.1_2.assigned_k2.png",
#        width = 6, height = 4)

p.pca.1_2.k2
```


```{r}
q_df_arrange_k3 <- read_csv("./out/snmf/q_df_arrange_k3.csv",
                            show_col_types = FALSE)
k3_pop_meta <- q_df_arrange_k3 %>%
  rowwise() %>%
  mutate(Pop_K3 = which.max(c(K1, K2, K3))) %>%
  select(SubjectID, K1, K2, K3, Pop_K3)

p.pca.1_2.k3 <- pca.df %>%
  filter(PC_x == "PC1",
         PC_y == "PC2") %>%
  left_join(k3_pop_meta, by = "SubjectID") %>%
  mutate(Pop_K3 = ifelse(K1 < 0.6 & K2 < 0.6 & K3 < 0.6, NA, Pop_K3)) %>%
  mutate(Pop_K3 = factor(Pop_K3)) %>%
  ggplot() +
  geom_point(aes(x = val_x, y = val_y, color = Pop_K3),
             size = 2) +
      scale_color_manual(name = "Genetic cluster",
                    values = c("grey80", cluster_cols[c(2,1, 3)]),
                    breaks = c(NA, 3, 1, 2),
                    labels = c("NA", "K1", "K2", "K3")) +
  xlab("PC1 (4.9% variation)") +
  ylab("PC2 (2.7% variation)") +
  theme_bw()
# ggsave(plot = p.pca.1_2.k3,
#        filename = "./plots/population_structure/p.pca.1_2.assigned_k3.png",
#        width = 6, height = 4)
p.pca.1_2.k3
```


```{r}
p.pca.1_5.k3 <- pca.df %>%
  filter(PC_x == "PC1",
         PC_y == "PC3") %>%
  left_join(k3_pop_meta, by = "SubjectID") %>%
  mutate(Pop_K3 = ifelse(K1 < 0.6 & K2 < 0.6 & K3 < 0.6, NA, Pop_K3)) %>%
  mutate(Pop_K3 = factor(Pop_K3)) %>%
  ggplot() +
  geom_point(aes(x = val_x, y = val_y, color = Pop_K3),
             size = 2) +
      scale_color_manual(name = "Genetic cluster",
                    values = c("grey80", cluster_cols[c(2,1, 3)]),
                    breaks = c(NA, 3, 1, 2),
                    labels = c("NA", "K1", "K2", "K3")) +
  xlab("PC1 (4.9% variation)") +
  ylab("PC2 (2.7% variation)") +
  theme_bw()
# ggsave(plot = p.pca.1_2.k3,
#        filename = "./plots/population_structure/p.pca.1_2.assigned_k3.png",
#        width = 6, height = 4)
p.pca.1_5.k3
```


```{r}
pc1.long.df <- pca.df %>%
  filter(PC_x == "PC1",
         PC_y == "PC1")
pc1.long.lm <- lm(val_x ~ Long, data = pc1.long.df)
summary(pc1.long.lm)
```


Mantel test


```{r}
# # euclidean dist
# genetic.dist.mat <- as.matrix(dist(obj, method = "euclidean"))
# # Proportion shared
# genetic.dist.mat <- as.matrix(1-propShared(geno.genind))
# PCA dist
pcs64.dist.mat <- readRDS("./data/radish/genetics/pca.dist.mat.64PCs.Rds")
pcs64.dist <- pcs64.dist.mat[lower.tri(pcs64.dist.mat)]

geo.dist.mat <- distm(geno$other$xy)
geo.dist <- geo.dist.mat[lower.tri(geo.dist.mat)]
```


```{r, message = FALSE}
dist.df <- tibble("Gen_dist" = as.numeric(pcs64.dist),
       "Geo_dist" = as.numeric(geo.dist)/1000)

p.gen.geo.dist <- dist.df %>%
  ggplot() +
  geom_point(aes(x = Geo_dist,
                 y = Gen_dist)) +
  geom_smooth(aes(x = Geo_dist,
                  y = Gen_dist)) +
  xlab("Geographic distance (km)") +
  ylab("Genetic distance (Euclidean)") +
  theme_bw()

ggsave(plot = p.gen.geo.dist,
       filename = "./plots/population_structure/p.gen.geo.dist.png",
       width = 6, height = 5)

p.gen.geo.dist
```

```{r}
dist.lm <- lm(Gen_dist ~ Geo_dist, data = dist.df)
summary(dist.lm)
```

```{r}
low.dist <- pcs64.dist.mat %>%
  as_tibble(rownames = "ID1") %>%
  pivot_longer(cols = 2:572, names_to = "ID2", values_to = "Distance") %>%
  filter(ID1 != ID2) %>%
  filter(Distance < 1)
low.dist
```

```{r}
low.dist.ids <- low.dist %>%
  pull(ID1)
meta %>%
  filter(SubjectID %in% low.dist.ids)
```

```{r}
kinship <- read_csv("./out/pcair-relate/buffer-10k/GSMNP-PCRelate-Kinship-3PCs.csv")
kinship %>%
  filter(ID1 == "GE0003467",
         ID2 == "NE01559735")
```



```{r}
gsmnp.mantel <- mantel.randtest(as.dist(pcs64.dist.mat), 
                                as.dist(geo.dist.mat))
gsmnp.mantel
```

```{r}
plot(gsmnp.mantel, nclass = 50)
```



