---
title: "IBE with radish"
author: "Matt DeSaix"
date: "2024-1-27"
output: html_document
---

```{r, message = F, warning = F}
library(radish)
library(tidyverse)
library(adegenet)
library(raster)
library(sf)
```

# Read in data

## Environmental data

```{r}
slope.lyr <- raster("./data/radish/covariates/grsm.slope.30m.tif")
elevation.lyr <- raster("./data/radish/covariates/grsm.elevation.30m.tif")
canopy.lyr <- raster("./data/radish/covariates/grsm.canopy.30m.tif")
nlcd.lyr <- raster("./data/radish/covariates/grsm.nlcd.30m.tif")

roads.lyr <- raster("./data/radish/covariates/grsm.roads.30m.tif")
water.lyr <- raster("./data/radish/covariates/grsm.water.30m.tif")
```

### Categorize nlcd

```{r}
nlcd.cat <- ratify(nlcd.lyr)
nlcd.rat <- levels(nlcd.cat)[[1]]
full.nlcd.df <- data.frame("ID" = c(11, 12, 
                                    21, 22, 23, 24,
                                    31,
                                    41, 42, 43,
                                    51, 52,
                                    71, 72, 73, 74,
                                    81, 82,
                                    90, 95),
                           "Landcover" = c("Open Water", "Perennial Ice/Snow",
                                           "Developed, Open Space", "Developed, Low Intensity", "Deveoped, Medium Intensity", "Developed, High Itensity",
                                           "Barren Land",
                                           "Deciduous Forest", "Evergreen Forest", "Mixed Forest",
                                           "Dwarf Scrub", "Shrub/Scrub",
                                           "Grassland/Herbaceous", "Sedge/Herbaceous", "Lichens", "Moss",
                                           "Pasture/Hay", "Cultivated Crops",
                                           "Woody Wetlands", "Emergent Herbaceous Wetlands"))

nlcd.rat <- merge(nlcd.rat, full.nlcd.df, by = "ID", all.x = TRUE)
levels(nlcd.cat) <- nlcd.rat
plot(nlcd.cat)
```

### Categorize roads and water

```{r}
roads.cat <- ratify(roads.lyr)
roads.rat <- levels(roads.cat)[[1]]
roads.rat$road <- c("Non-road", "Road")
levels(roads.cat) <- roads.rat
plot(roads.cat)
```

```{r}
water.cat <- ratify(water.lyr)
water.rat <- levels(water.cat)[[1]]
water.rat$StreamOrder <- c(NA, 1:7)
levels(water.cat) <- water.rat
plot(water.cat)
```

```{r}
water.cat.binary <- ratify(water.lyr)
water.cat.binary[water.cat.binary >= 1] <- 1
water.rat.binary <- data.frame("ID" = c(0,1))
water.rat.binary$StreamOrder <- c(NA, 1)
levels(water.cat.binary) <- water.rat.binary
plot(water.cat.binary)
```


```{r}
water.cat.factor <- ratify(water.lyr)
water.cat.factor[water.cat.factor >= 1 & water.cat.factor < 5] <- 1
water.cat.factor[water.cat.factor >= 5] <- 2
water.rat.factor <- data.frame("ID" = c(0,1, 2))
water.rat.factor$StreamOrder <- c(NA, 1, 2)
levels(water.cat.factor) <- water.rat.factor
plot(water.cat.factor)
```


### Genetic data


compare PC estimates

```{r}
pcs10 <- readRDS("./data/radish/genetics/pca.dist.mat.10PCs.Rds")
pcs64 <- readRDS("./data/radish/genetics/pca.dist.mat.64PCs.Rds")

pc.dist.df <- data.frame("pcs10" = as.vector(pcs10),
                         "pcs64" = as.vector(pcs64))
pc.dist.df %>%
  ggplot(aes(x = pcs10, y = pcs64)) +
  geom_point() +
  coord_equal()
```



#***********************************************************************
# Radish

## Prepare inputs

### Samples

```{r}
e <- c(-84.029, -83.005, 35.443, 35.762)
# scale_covs <- raster::stack(scale(elevation.lyr), scale(slope.lyr), scale(canopy.lyr),
#                             nlcd.cat,
#                             roads.cat, water.cat,
#                             water.cat.binary, water.cat.factor) %>%
#   crop(e) %>%
#   raster::stack()
scale_covs <- raster::stack(elevation.lyr, slope.lyr, canopy.lyr,
                            nlcd.cat,
                            roads.cat, water.cat,
                            water.cat.binary, water.cat.factor) %>%
  crop(e) %>%
  raster::stack()
names(scale_covs) <- c("elevation", "slope", "canopy", "nlcd",
                       "roads", "water", "water_binary", "water_factor")

```

Aggregate and crop

```{r}
# small_e <- c(-83.9, -83.75, 35.4, 35.65)
small_e <- c(-83.65, -83.3, 35.5, 35.7)
factor_val <- 4
scale_covs_small <- crop(scale_covs, small_e) %>%
  raster::aggregate(fact = factor_val, fun = modal) %>%
  raster::stack()
plot(scale_covs_small)
```

Need to reclassify all the categorical rasters

```{r}
# NLCD
scale_covs_small[["nlcd"]] <- ratify(scale_covs_small[["nlcd"]])
nlcd.rat.small <- levels(scale_covs_small[["nlcd"]])[[1]] %>%
  merge(full.nlcd.df, by = "ID", all.x = TRUE)
levels(scale_covs_small[["nlcd"]]) <- nlcd.rat.small

# Roads
scale_covs_small[["roads"]] <- ratify(scale_covs_small[["roads"]])
roads.rat.small <- levels(scale_covs_small[["roads"]])[[1]]
roads.rat.small$road <- c("Non-road", "Road")
levels(scale_covs_small[["roads"]]) <- roads.rat.small

# Water
scale_covs_small[["water"]] <- ratify(scale_covs_small[["water"]])
water.rat.small <- levels(scale_covs_small[["water"]])[[1]]
water.rat.small <- merge(water.rat.small,
                         water.rat, by = "ID", all.x = T)
levels(scale_covs_small[["water"]]) <- water.rat.small

# Water binary
scale_covs_small[["water_binary"]] <- ratify(scale_covs_small[["water_binary"]])
water.rat.binary.small <- levels(scale_covs_small[["water_binary"]])[[1]]
water.rat.binary.small <- merge(water.rat.binary.small,
                         water.rat.binary, by = "ID", all.x = T)
levels(scale_covs_small[["water_binary"]]) <- water.rat.binary.small

# Water factor
scale_covs_small[["water_factor"]] <- ratify(scale_covs_small[["water_factor"]])
water.rat.factor.small <- levels(scale_covs_small[["water_factor"]])[[1]]
water.rat.factor.small <- merge(water.rat.factor.small,
                         water.rat.factor, by = "ID", all.x = T)
levels(scale_covs_small[["water_factor"]]) <- water.rat.factor.small
```


```{r}
meta <- read_csv("./data/genotypes/buffer-10k/grsm-10k-meta.csv",
                 show_col_types = FALSE) %>%
  mutate(Long_jitter = jitter(Long, factor = 1),
         Lat_jitter = jitter(Lat, factor = 1),
         Long_lat = paste0(Long, "_", Lat),
         Long_lat_jitter = paste0(Long_jitter, "_", Lat_jitter))
ids.filter <- meta %>%
  filter(Long > small_e[1],
         Long < small_e[2],
         Lat > small_e[3],
         Lat < small_e[4])

input_samples <- SpatialPoints(coords = ids.filter[,c("Long", "Lat")])
```

```{r}
plot(scale_covs_small[[1]])
points(input_samples)
```

```{r}
table(values(scale_covs_small[["nlcd"]]))
```

## Run Radish

```{r}
surface <- conductance_surface(covariates = scale_covs_small,
                               coords = input_samples,
                               directions = 8)
```

```{r}
ids.index <- which(meta$SubjectID %in% ids.filter$SubjectID)
pca.dist.mat <- readRDS("./data/radish/genetics/pca.dist.mat.RDS")
gen_input <- pca.dist.mat[ids.index, ids.index]
```

```{r}
fit_mlpe <- radish(gen_input ~ elevation + water_factor
                   
                   ,
                   data = surface, 
                   conductance_model = radish::loglinear_conductance, 
                   measurement_model = radish::mlpe)

summary(fit_mlpe)
```


```{r}
plot(fitted(fit_mlpe, "distance"), gen_input, pch = 19,
     xlab = "Optimized resistance distance", ylab = "Dc")
```

```{r}
## Plot fitted conductance surface
fitted_conductance <- conductance(surface, fit_mlpe, quantile = 0.95)

plot(log(fitted_conductance[["est"]]), 
     main = "Fitted conductance surface\n(some variables)")
```


### Check landscape data


```{r}
scale_covs_agg4 <- readRDS("./data/radish/intermediary/30m_4agg/covariates_4agg.Rds")
scale_covs_agg4
```


```{r}
pairwise_corrs_agg4 <- layerStats(scale_covs_agg4, 'pearson', na.rm=T)

corr_matrix_agg4 <- pairwise_corrs_agg4$'pearson correlation coefficient'
corr_matrix_agg4
```

```{r}
meta <- read_csv("./data/genotypes/buffer-10k/grsm-10k-meta.csv",
                 show_col_types = FALSE) %>%
  mutate(Long_jitter = jitter(Long, factor = 1),
         Lat_jitter = jitter(Lat, factor = 1),
         Long_lat = paste0(Long, "_", Lat),
         Long_lat_jitter = paste0(Long_jitter, "_", Lat_jitter))

input_samples <- SpatialPoints(coords = meta[,c("Long", "Lat")])

agg4_vals <- extract(scale_covs_agg4, input_samples)
samples_corr_agg4 <- cor(agg4_vals)
samples_corr_agg4
```





```{r}
plot(scale_covs_agg4[[c("elevation", "slope", "canopy", "roads", "water_factor")]])
```



